var ids = [{id: 'alvarados-bakery-pharr-tx-2', twitter: 'alvaradostreet',name: 'Alvarados Bakery'},
{id: 'big-apple-bagels-edinburg-tx', twitter: 'bigapplebagels',name: 'Big Apple Bagels'},
{id: 'double-eagle-brewery-and-eatery-kissimmee-fl', twitter: 'beefobrady',name: 'Double Eagle Brewery and Eatery'},
{id: 'big-boy-restaurant-el-paso-tx', twitter: 'officialbigboy',name: 'Big Boy Restaurant'},
{id: 'burgers-and-beer-el-centro-ca', twitter: 'burgersnbeer',name: 'Burgers and Beer'},
{id: 'cookie-s-by-design-el-paso-tx', twitter: 'cookiesbydesign',name: 'Cookie\'s by Design'},
{id: 'cupcake-hearts-kissimmee-fl', twitter: 'cupcakehearts1',name: 'Cupcake Hearts'},
{id: 'ripe-eatery-and-market-el-paso-tx', twitter: 'ripeeatery',name: 'Ripe Eatery and Market'},
{id: 'flippers-pizzeria-kissimmee-fl', twitter: 'flipperspizzaus',name: 'Flippers Pizzeria'},
{id: 'fuddruckers-eagle-pass-tx', twitter: 'fuddruckers',name: 'Fuddruckers'},
{id: 'furr-s-family-dining-el-paso-tx-1', twitter: 'furrs',name: 'Furr\'s Family Dining'},
{id: 'gloria-jean-s-coffee-mcallen-tx', twitter: 'gloriajeansusa',name: 'Gloria Jean\'s Coffee'},
{id: 'godfathers-pizza-saint-cloud-fl', twitter: 'godfatherspizza',name: 'Godfathers Pizza'},
{id: 'greenery-bakery-cafe-and-grill-el-paso-tx', twitter: 'gotogreenery',name: 'Greenery Bakery Cafe and Grill'},
{id: 'hope-and-anchor-el-paso-tx', twitter: 'hope_and_anchor',name: 'Hope and Anchor'},
{id: 'las-salsas-el-centro-ca', twitter: 'viva_lasalsa',name: 'Las Salsas'},
{id: 'los-pasteles-bakery-coffee-shop-laredo-tx', twitter: 'localedge',name: 'Los Pasteles Bakery Coffee Shop'},
{id: 'maverick-s-bar-and-grill-el-paso-tx', twitter: 'mavsbargrill',name: 'Maverick\'s Bar and Grill'},
{id: 'nopalito-restaurant-las-cruces-nm', twitter: 'nopalitogaleria',name: 'Nopalito Restaurant'},
{id: 'full-house-kissimmee-fl', twitter: 'myoldtownusa',name: 'Full House'},
{id: 'papa-murphys-take-n-bake-san-benito-tx', twitter: 'papamurphyspizza',name: 'Papa Murphys Take n Bake'},
{id: 'pizza-inn-las-cruces-nm', twitter: 'pizzainn_inc',name: 'Pizza Inn'},
{id: 'the-bean-mesilla-nm', twitter: 'thebeanmesilla',name: 'The Bean'},
{id: 'coffee-zone-edinburg-tx', twitter: 'coffeezonergv',name: 'Coffee Zone'},
{id: 'tila-s-mexican-restaurant-harlingen-tx', twitter: 'tilastacotruck',name: 'Tila\'s Mexican Restaurant'},
{id: 'tony-roma-s-mcallen-tx-1', twitter: 'tonyromas',name: 'Tony Roma\'s'},
{id: 'tubac-jack-s-saloon-tubac-az', twitter: 'tubacjacks',name: 'Tubac Jack\'s Saloon'},
{id: 'uno-chicago-grill-laredo-tx', twitter: 'unochicagogrill',name: 'Uno Chicago Grill'},
{id: 'capone-s-dinner-and-show-kissimmee-fl-1', twitter: 'alcaponesshow',name: 'Capone\'s Dinner and Show'},
{id: 'sandwich-shop-kissimmee-fl', twitter: 'andys_manoa',name: 'Sandwich Shop'},
{id: 'aneshly-cakes-el-paso-tx', twitter: 'aneshlycakes',name: 'Aneshly Cakes'},
{id: 'tv-azteca-laredo-tx', twitter: 'aztecamexcom',name: 'Tv-Azteca'},
{id: 'fox-and-hounds-kissimmee-fl', twitter: 'the_foxandhound',name: 'Fox and Hounds'},
{id: 'baja-fresh-el-paso-tx', twitter: 'boldbajafresh',name: 'Baja Fresh'},
{id: 'bar-b-cutie-mcallen-tx', twitter: 'barbcutie',name: 'Bar-B-Cutie'},
{id: 'barnie-s-coffee-and-tea-co-kissimmee-fl-2', twitter: 'barniescoffee',name: 'Barnie\'s Coffee and Tea Co.'},
{id: 'cactus-restaurant-rio-grande-city-tx', twitter: 'eatatcactus',name: 'Cactus Restaurant'},
{id: 'cafe-kranzler-south-padre-island-tx', twitter: 'cafekranzler',name: 'Cafe Kranzler'},
{id: 'anthony-s-pizza-el-paso-tx', twitter: 'charleys',name: 'Anthony\'s Pizza'},
{id: 'chevy-s-fresh-mex-restaurants-kissimmee-fl', twitter: 'chevysfreshmex',name: 'Chevy\'s Fresh Mex Restaurants'},
{id: 'rice-and-beans-cocina-latina-kissimmee-fl', twitter: 'riceandbeansfl',name: 'Rice and Beans Cocina Latina'},
{id: 'cynthia-s-cakes-edinburg-tx', twitter: 'cynthiascakes',name: 'Cynthia\'s Cakes'},
{id: 'dion-s-pizza-las-cruces-nm', twitter: 'dionspizza',name: 'Dion\'s Pizza'},
{id: 'el-divino-dining-cocktails-mcallen-tx', twitter: 'eldivinorgv',name: 'El Divino Dining & Cocktails'},
{id: 'el-meson-de-san-augustine-laredo-tx', twitter: 'elmesonsagustin',name: 'El Meson De San Augustine'},
{id: 'empire-lounge-mcallen-tx', twitter: 'empireloungergv',name: 'Empire Lounge'},
{id: 'extreme-pizza-kissimmee-fl', twitter: 'extreme_pizza',name: 'Extreme Pizza'},
{id: 'farmer-boys-el-centro-ca', twitter: 'farmerboys',name: 'Farmer Boys'},
{id: 'freshens-laredo-tx', twitter: 'freshens',name: 'Freshens'},
{id: 'funtastico-el-paso-tx', twitter: 'funtasticofun',name: 'Funtastico'},
{id: 'garduno-s-chili-packing-co-las-cruces-nm', twitter: 'gardunosnm',name: 'Garduno\'s Chili Packing Co.'},
{id: 'garufa-argentinean-restaurant-el-paso-tx', twitter: 'garufaelpaso',name: 'Garufa Argentinean Restaurant'},
{id: 'gator-s-dockside-kissimmee-fl', twitter: 'gatorsdkside',name: 'Gator\'s Dockside'},
{id: 'geske-s-fire-grill-el-paso-tx', twitter: 'geskes_grill',name: 'Geske\'s Fire Grill'},
{id: 'gloria-s-restaurant-eagle-pass-tx', twitter: 'gloriasdfw',name: 'Gloria\'s Restaurant'},
{id: 'golden-krust-kissimmee-fl', twitter: 'goldenkrustbkry',name: 'Golden Krust'},
{id: 'good-luck-cafe-el-paso-tx', twitter: 'goodluckcafe',name: 'Good Luck Cafe'},
{id: 'great-wall-restaurant-saint-cloud-fl', twitter: 'thegreatwallma',name: 'Great Wall Restaurant'},
{id: 'hamburger-stand-el-paso-tx', twitter: '1hamburgerstand',name: 'Hamburger Stand'},
{id: 'hardee-s-kissimmee-fl', twitter: 'hardees',name: 'Hardee\'s'},
{id: 'hello-day-cafe-el-paso-tx', twitter: 'hellodaycafe',name: 'Hello Day Cafe'},
{id: 'high-five-frozen-yogurt-saint-cloud-fl', twitter: 'highfivefroyo',name: 'High Five Frozen Yogurt'},
{id: 'hukkah-lounge-south-padre-island-tx', twitter: 'hookahhookah',name: 'Hukkah Lounge'},
{id: 'house-pasture-cattle-co-concan-tx', twitter: 'housepasture',name: 'House Pasture Cattle Co.'},
{id: 'incredibles-el-paso-tx', twitter: 'incrediblepizza',name: 'Incredibles'},
{id: 'international-delights-las-cruces-nm', twitter: 'cafe_id',name: 'International Delights'},
{id: 'jc-s-new-york-pizza-department-las-vegas-nm', twitter: 'jcnypd',name: 'JC\'s New York Pizza Department'},
{id: 'jerusalem-international-foods-el-paso-tx', twitter: 'jerusalem_grill',name: 'Jerusalem International Foods'},
{id: 'juanita-s-mexican-food-anthony-tx', twitter: 'juanitasiii',name: 'Juanita\'s Mexican Food'},
{id: 'lotus-inn-chinese-cuisine-toronto-tx', twitter: 'justeatca',name: 'Lotus Inn Chinese Cuisine'},
{id: 'charley-s-steak-house-and-seafood-grille-kissimmee-fl', twitter: 'kobe_steakhouse',name: 'Charley\'s Steak House and Seafood Grille'},
{id: 'kolache-factory-mcallen-tx', twitter: 'kolachefactory',name: 'Kolache Factory'},
{id: 'la-posta-de-mesilla-mesilla-nm', twitter: 'lapostamesilla',name: 'La Posta de Mesilla'},
{id: 'larissa-s-cake-shop-zapata-tx', twitter: 'larissascakes',name: 'Larissa\'s Cake Shop'},
{id: 'el-taquito-pharr-tx', twitter: 'letseat',name: 'El Taquito'},
{id: 'lone-star-steakhouse-and-saloon-mcallen-tx', twitter: 'lonestarsteak',name: 'Lone Star Steakhouse and Saloon'},
{id: 'loop-gyros-kissimmee-fl', twitter: 'loopgyros',name: 'Loop Gyros'},
{id: 'manjar-el-paso-tx', twitter: 'manjarsweets',name: 'Manjar'},
{id: 'max-s-cafe-kissimmee-fl', twitter: 'marketstcafe',name: 'Max\'s Cafe'},
{id: 'meat-n-fire-saint-cloud-fl', twitter: 'meatnfire',name: 'Meat n Fire'},
{id: 'mexico-lindo-holtville-ca', twitter: 'mexico_lindo',name: 'Mexico Lindo'},
{id: 'mimi-s-cafe-kissimmee-fl', twitter: 'mimis_cafe',name: 'Mimi\'s Cafe'},
{id: 'mi-piaci-el-paso-tx', twitter: 'mipiacielpaso',name: 'Mi Piaci'},
{id: 'mi-tierras-cafe-pearsall-tx', twitter: 'mi_tierra_cafe',name: 'Mi Tierras Cafe'},
{id: 'moe-s-southwest-grill-kissimmee-fl', twitter: 'moes_hq',name: 'Moe\'s Southwest Grill'},
{id: 'nonnavivi-rio-rico-az', twitter: 'nonnavivi',name: 'Nonnavivi'},
{id: 'nuovo-cappetto-el-paso-tx', twitter: 'nuovocappetto',name: 'Nuovo Cappetto'},
{id: 'new-york-bagel-cafe-and-deli-el-paso-tx', twitter: 'nybagelcafedeli',name: 'New York Bagel Cafe and Deli'},
{id: 'oasis-bistro-and-lounge-el-paso-tx', twitter: 'elpasooasis',name: 'Oasis Bistro and Lounge'},
{id: 'ostioneria-michoacan-mcallen-tx', twitter: 'ostionerias',name: 'Ostioneria Michoacan'},
{id: 'the-palomino-el-paso-tx', twitter: 'tavern_palomino',name: 'The Palomino'},
{id: 'pancho-villas-restaurant-el-paso-tx', twitter: 'panchovillasres',name: 'Pancho Villas Restaurant'},
{id: 'pancho-villa-restaurant-penitas-tx', twitter: 'panchovillava',name: 'Pancho Villa Restaurant'},
{id: 'gathering-grounds-patagonia-az', twitter: 'patagoniasbuzz',name: 'Gathering Grounds'},
{id: 'pizza-patron-brownsville-tx-1', twitter: 'pizzapatron',name: 'Pizza Patron'},
{id: 'pizza-plus-kissimmee-fl', twitter: 'pizzaplus',name: 'Pizza Plus'},
{id: 'planet-smoothie-saint-cloud-fl', twitter: 'planetsmoothie',name: 'Planet Smoothie'},
{id: 'the-pot-au-feu-el-paso-tx', twitter: 'thepotaufeu',name: 'The Pot Au Feu'},
{id: 'pretzelmaker-el-paso-tx', twitter: 'pretzelmaker',name: 'Pretzelmaker'},
{id: 'the-ristretto-edinburg-tx', twitter: 'ristrettoevents',name: 'The Ristretto'},
{id: 'roberto-s-taco-shop-brawley-ca', twitter: 'sdrobertos',name: 'Roberto\'s Taco Shop'},
{id: 'santa-fe-steakhouse-mcallen-tx', twitter: 'festeak',name: 'Santa Fe Steakhouse'},
{id: 'shakey-s-pizza-parlor-nogales-az', twitter: 'shakeysusa',name: 'Shakey\'s Pizza Parlor'},
{id: 'shipley-donuts-pharr-tx', twitter: 'shipleydo_nuts',name: 'Shipley Donuts'},
{id: 'siempre-natural-pharr-tx', twitter: 'sn_restaurant',name: 'Siempre Natural'},
{id: 'solo-empanadas-y-mas-mission-tx', twitter: 'statuses',name: 'SOLO Empanadas Y MAS'},
{id: 'sombrero-mexican-food-el-centro-ca', twitter: 'sombreromexican',name: 'Sombrero Mexican Food'},
{id: 'sunset-grill-las-cruces-nm', twitter: 'sonomaranchgolf',name: 'Sunset Grill'},
{id: 'sparky-s-hatch-nm', twitter: 'sparkysburgers',name: 'Sparky\'s'},
{id: 'speedy-stop-mcallen-tx', twitter: 'speedystop',name: 'Speedy Stop'},
{id: 'surf-city-squeeze-el-centro-ca', twitter: 'surfcitysqueeze',name: 'Surf City Squeeze'},
{id: 'teto-s-tacos-el-paso-tx', twitter: 'tacoholics',name: 'Teto\'s Tacos'},
{id: 'bandits-roadhouse-bar-b-que-mission-tx', twitter: 'tacorico1',name: 'Bandits Roadhouse Bar-B-Que'},
{id: 'taqueria-arandas-kingsville-tx', twitter: 'taqueriaarandas',name: 'Taqueria Arandas'},
{id: 'aloha-terriyaki-kissimmee-fl', twitter: 'teriyaki_exp',name: 'Aloha Terriyaki'},
{id: 'the-pizza-joint-el-paso-tx', twitter: 'thepizzajointep',name: 'The Pizza Joint'},
{id: 'the-big-slice-toronto-tx', twitter: 'thebigsliceto',name: 'The Big Slice'},
{id: 'the-burger-s-priest-toronto-tx', twitter: 'burgerspriest',name: 'The Burger\'s Priest'},
{id: 'celebration-town-tavern-celebration-fl', twitter: 'towntavern',name: 'Celebration Town Tavern'},
{id: 'palms-kissimmee-fl', twitter: 'palmshotelvilla',name: 'Palms'},
{id: 'the-pizzeria-harlingen-tx', twitter: 'the_pizzeria',name: 'The Pizzeria'},
{id: 'tijuana-flats-kissimmee-fl', twitter: 'tijuanaflats',name: 'Tijuana Flats'},
{id: 'tortilleria-el-paso-tx', twitter: 'tortillasdelsol',name: 'Tortilleria'},
{id: 'tosca-stone-oven-pizzeria-el-paso-tx', twitter: 'toscapizzeria',name: 'Tosca Stone Oven Pizzeria'},
{id: 'tropical-smoothie-cafe-kissimmee-fl', twitter: 'tsmoothiecafe',name: 'Tropical Smoothie Cafe'},
{id: 'wildside-kissimmee-fl', twitter: 'wildsidebbq',name: 'Wildside'},
{id: 'wing-daddy-s-el-paso-tx-1', twitter: 'wing_daddys',name: 'Wing Daddy\'s'},
{id: 'wingers-el-paso-tx', twitter: 'wingersroad',name: 'Wingers'},
{id: 'winghouse-of-kissimmee-kissimmee-fl', twitter: 'kerswinghouse',name: 'Winghouse of Kissimmee'},
{id: 'wisdom-s-cafe-tumacacori-az', twitter: 'wisdomscafe',name: 'Wisdom\'s Cafe'}];

module.exports = ids;