#!/bin/sh
mkdir -p /home/caura/webapps/hack/run
pid=$(/sbin/pidof /home/caura/webapps/hack/bin/node)
if echo "$pid" | grep -q " "; then
    pid=""
fi
if [ -n "$pid" ]; then
  user=$(ps -p $pid -o user | tail -n 1)
  if [ $user = "caura" ]; then
    kill "$pid"
    rm -f /home/caura/webapps/hack/run/node.pid
  fi
fi
